version: "3.8"
services:


  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - backend
    command: --auth

  backend:
    depends_on:
      - mongodb
    build: ./Backend/Backend
    restart: on-failure
    env_file: .env
    ports:
      - "9001:9001"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/
    volumes:
      - C:/Users/Hp/Desktop/my_projects/db:/data/db
    stdin_open: true
    tty: true
    networks:
      - backend

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - backend



  ai_api:

     build: ./AI
     restart: on-failure
     env_file: .env
     ports:
       - "5000:5000"
     networks:
       - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
